Repository code4recovery/12-step-meeting-list, pull requests merged in 2023-03, with the labels that each got.

#1084 add custom descriptions function
  includes/functions.php
  readme.txt
Labels: front end

#1087 Feeds import puts 12x12 meetings in notes
  includes/functions.php
Labels: import

#1097 Fixing undefined index error on upcoming meetings shortcode
  includes/shortcodes.php
Labels: bug, front end

#1102 Fix URLs in [tsml_types_list] & [tsml_regions_list] shortcodes
  includes/shortcodes.php
Labels: bug, front end
